"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { getStaffWith, requirePermission } from "@/lib/session";
import { can, isStaff } from "@/lib/permissions";
import { canSetUserStatus, type Role } from "@/lib/admin-guards";
import { audit } from "@/lib/audit";

export type AdminActionState = { error?: string; ok?: boolean };

const customerIdentitySchema = z.object({
  name: z.string().min(2).max(100),
  email: z.email("Enter a valid email address."),
});

const TAG_STATUSES = ["ACTIVE", "LOST", "DEACTIVATED"] as const;
type TagStatus = (typeof TAG_STATUSES)[number];

// --- Users --------------------------------------------------------------

/** Suspend or reactivate a customer. Destructive, so super admins only. */
export async function setUserStatusAction(userId: string, status: "ACTIVE" | "SUSPENDED") {
  const actor = await requirePermission("destructive");
  if (status !== "ACTIVE" && status !== "SUSPENDED") throw new Error("Invalid status.");

  const target = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true, name: true, email: true, role: true, status: true },
  });
  if (!target) throw new Error("User not found.");

  // Suspending an admin is a demotion in disguise, and suspending yourself
  // locks you out of the console. Both go through /admin/admins instead.
  const guard = canSetUserStatus({
    actorId: actor.id,
    targetId: target.id,
    targetRole: target.role as Role,
  });
  if (!guard.ok) throw new Error(guard.reason);
  if (target.status === status) return;

  await prisma.user.update({ where: { id: target.id }, data: { status } });
  await audit(
    actor.id,
    status === "SUSPENDED" ? "user.suspend" : "user.reactivate",
    { type: "user", id: target.id },
    `${status === "SUSPENDED" ? "Suspended" : "Reactivated"} ${target.name} (${target.email})`,
  );
  revalidatePath("/admin/users");
  revalidatePath(`/admin/users/${target.id}`);
}

/**
 * Correct a customer's name or sign-in email on their behalf.
 *
 * A support desk needs this — people mistype their own email at signup and
 * then cannot receive a reset link. Restricted to customers: an admin's own
 * details are changed at /admin/profile, and another admin's are theirs alone.
 */
export async function updateCustomerIdentityAction(
  userId: string,
  _prev: AdminActionState,
  formData: FormData,
): Promise<AdminActionState> {
  if (!(await getStaffWith("users.manage"))) return { error: "Not authorized." };

  const parsed = customerIdentitySchema.safeParse({
    name: formData.get("name"),
    email: formData.get("email"),
  });
  if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Invalid input" };

  const target = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true, role: true },
  });
  if (!target) return { error: "User not found." };
  if (isStaff(target.role)) return { error: "Admin accounts are edited by their owners at /admin/profile." };

  const email = parsed.data.email.trim().toLowerCase();
  const clash = await prisma.user.findFirst({
    where: { email, NOT: { id: target.id } },
    select: { id: true },
  });
  if (clash) return { error: "Another account already uses that email." };

  await prisma.user.update({
    where: { id: target.id },
    data: { name: parsed.data.name.trim(), email },
  });

  revalidatePath("/admin/users");
  revalidatePath(`/admin/users/${target.id}`);
  return { ok: true };
}

// --- Tags ---------------------------------------------------------------
// Tags are generated by customers against QR slots they bought, so there is no
// inventory to assign or reclaim. Any admin can mark a tag lost or active for a
// support case. Taking one down — or undoing a takedown — is destructive and
// belongs to super admins, and is recorded in the activity log.

export async function setTagStatusAction(tagId: string, status: TagStatus): Promise<AdminActionState> {
  const actor = await getStaffWith("tags.manage");
  if (!actor) return { error: "Not authorized." };
  if (!TAG_STATUSES.includes(status)) return { error: "Invalid status." };

  const tag = await prisma.tag.findUnique({
    where: { id: tagId },
    select: { id: true, shortCode: true, status: true },
  });
  if (!tag) return { error: "Tag not found." };
  if (tag.status === status) return { ok: true };

  const takedown = status === "DEACTIVATED" || tag.status === "DEACTIVATED";
  if (takedown && !can(actor.role, "destructive")) {
    return { error: "Only a super admin can deactivate a QR code or undo a takedown." };
  }

  await prisma.tag.update({ where: { id: tag.id }, data: { status } });
  if (takedown) {
    await audit(
      actor.id,
      status === "DEACTIVATED" ? "tag.deactivate" : "tag.reactivate",
      { type: "tag", id: tag.id },
      status === "DEACTIVATED"
        ? `Deactivated /t/${tag.shortCode}`
        : `Reactivated /t/${tag.shortCode} (now ${status.toLowerCase()})`,
    );
  }

  revalidatePath("/admin/tags");
  revalidatePath(`/admin/tags/${tag.id}`);
  revalidatePath("/admin");
  return { ok: true };
}

// --- Abuse reports --------------------------------------------------

export async function resolveAbuseReportAction(
  reportId: string,
  status: "REVIEWING" | "RESOLVED" | "DISMISSED",
) {
  await requirePermission("console.view");
  if (!["REVIEWING", "RESOLVED", "DISMISSED"].includes(status)) throw new Error("Invalid status.");
  await prisma.abuseReport.update({
    where: { id: reportId },
    data: { status, resolvedAt: status === "RESOLVED" || status === "DISMISSED" ? new Date() : null },
  });
  revalidatePath("/admin/abuse-reports");
}
