"use server";

import { revalidatePath } from "next/cache";
import { getAdmin, requireAdmin } from "@/lib/session";
import { prisma } from "@/lib/prisma";

export type AdminActionState = { error?: string; ok?: boolean };

function revalidateTagViews() {
  revalidatePath("/admin/tags");
  revalidatePath("/admin");
}

// --- Users --------------------------------------------------------------

export async function setUserStatusAction(userId: string, status: "ACTIVE" | "SUSPENDED") {
  await requireAdmin();

  const target = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true, role: true },
  });
  if (!target) throw new Error("User not found.");

  // Admin accounts are not customer accounts and must not be suspended or
  // toggled from this screen. Managing admins is a deliberate, separate
  // operation (currently seed/DB only).
  if (target.role === "ADMIN") {
    throw new Error("Admin accounts cannot be modified here.");
  }

  await prisma.user.update({ where: { id: target.id }, data: { status } });
  revalidatePath("/admin/users");
}

// --- Tags ---------------------------------------------------------------
// Tags are generated by customers against QR slots they bought, so there is no
// inventory to assign or reclaim. An admin can still change a tag's status —
// support cases, abuse takedowns — but never reassign one.

export async function setTagStatusAction(
  tagId: string,
  status: "ACTIVE" | "LOST" | "DEACTIVATED",
): Promise<AdminActionState> {
  const admin = await getAdmin();
  if (!admin) return { error: "Forbidden." };

  const tag = await prisma.tag.findUnique({ where: { id: tagId }, select: { id: true } });
  if (!tag) return { error: "Tag not found." };

  await prisma.tag.update({ where: { id: tag.id }, data: { status } });
  revalidateTagViews();
  return { ok: true };
}

// --- Abuse reports --------------------------------------------------

export async function resolveAbuseReportAction(
  reportId: string,
  status: "REVIEWING" | "RESOLVED" | "DISMISSED"
) {
  await requireAdmin();
  await prisma.abuseReport.update({
    where: { id: reportId },
    data: { status, resolvedAt: status === "RESOLVED" || status === "DISMISSED" ? new Date() : null },
  });
  revalidatePath("/admin/abuse-reports");
}
