import Link from "next/link";
import { redirect } from "next/navigation";
import { getAdmin } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import type { Prisma } from "@prisma/client";
import { TagStatusSelect } from "./tag-status-select";

export const dynamic = "force-dynamic";

// Tags are generated by customers against QR slots they bought, so this page
// is a register of what exists rather than an inventory to hand out.
const STATUSES = ["ACTIVE", "LOST", "DEACTIVATED"] as const;

export default async function AdminTagsPage({
  searchParams,
}: {
  searchParams: Promise<{ status?: string; product?: string }>;
}) {
  if (!(await getAdmin())) redirect("/dashboard");
  const sp = await searchParams;

  const where: Prisma.TagWhereInput = {};
  if (STATUSES.includes(sp.status as (typeof STATUSES)[number])) {
    where.status = sp.status as (typeof STATUSES)[number];
  }
  if (sp.product) where.productId = sp.product;

  const [tags, byStatus, products] = await Promise.all([
    prisma.tag.findMany({
      where,
      include: {
        user: { select: { name: true, email: true } },
        product: { select: { name: true } },
        theme: { select: { name: true } },
        _count: { select: { scanEvents: true } },
      },
      orderBy: { createdAt: "desc" },
      take: 300,
    }),
    prisma.tag.groupBy({ by: ["status"], _count: { _all: true } }),
    prisma.product.findMany({ select: { id: true, name: true }, orderBy: { sortOrder: "asc" } }),
  ]);

  const count = (s: string) => byStatus.find((g) => g.status === s)?._count._all ?? 0;

  return (
    <div>
      <h1 className="text-2xl font-bold">Tags</h1>
      <p className="mt-1 text-sm text-black/60">
        Every QR a customer has generated. Codes are created in the client area against
        purchased slots — there is no inventory to assign.
      </p>

      <div className="mt-5 flex flex-wrap gap-2 text-sm">
        <Link
          href="/admin/tags"
          className={`rounded-lg border px-3 py-1.5 ${!sp.status ? "border-emerald-600 bg-emerald-50 text-emerald-800" : "border-black/15 hover:bg-black/5"}`}
        >
          All ({byStatus.reduce((n, g) => n + g._count._all, 0)})
        </Link>
        {STATUSES.map((s) => (
          <Link
            key={s}
            href={`/admin/tags?status=${s}`}
            className={`rounded-lg border px-3 py-1.5 ${sp.status === s ? "border-emerald-600 bg-emerald-50 text-emerald-800" : "border-black/15 hover:bg-black/5"}`}
          >
            {s} ({count(s)})
          </Link>
        ))}
      </div>

      {products.length > 0 && (
        <div className="mt-3 flex flex-wrap gap-2 text-xs">
          <Link
            href={sp.status ? `/admin/tags?status=${sp.status}` : "/admin/tags"}
            className="rounded-full border border-black/15 px-2.5 py-1 hover:bg-black/5"
          >
            Any product
          </Link>
          {products.map((p) => (
            <Link
              key={p.id}
              href={`/admin/tags?product=${p.id}`}
              className={`rounded-full border px-2.5 py-1 ${sp.product === p.id ? "border-emerald-600 bg-emerald-50" : "border-black/15 hover:bg-black/5"}`}
            >
              {p.name}
            </Link>
          ))}
        </div>
      )}

      <div className="mt-6 overflow-x-auto rounded-xl border border-black/10 bg-white">
        <table className="w-full text-sm">
          <thead className="border-b border-black/10 text-left text-xs uppercase tracking-wide text-black/40">
            <tr>
              <th className="px-4 py-3 font-medium">Code</th>
              <th className="px-4 py-3 font-medium">Owner</th>
              <th className="px-4 py-3 font-medium">Product / theme</th>
              <th className="px-4 py-3 font-medium">Scans</th>
              <th className="px-4 py-3 font-medium">Status</th>
            </tr>
          </thead>
          <tbody>
            {tags.length === 0 ? (
              <tr>
                <td colSpan={5} className="px-4 py-8 text-center text-black/50">
                  No tags match this filter.
                </td>
              </tr>
            ) : (
              tags.map((t) => (
                <tr key={t.id} className="border-b border-black/5 last:border-b-0">
                  <td className="px-4 py-3">
                    <Link href={`/admin/tags/${t.id}`} className="font-mono text-xs hover:underline">
                      /t/{t.shortCode}
                    </Link>
                  </td>
                  <td className="px-4 py-3">
                    {t.user.name}
                    <div className="text-xs text-black/40">{t.user.email}</div>
                  </td>
                  <td className="px-4 py-3 text-xs text-black/60">
                    {t.product?.name ?? "—"}
                    {t.theme ? ` · ${t.theme.name}` : ""}
                  </td>
                  <td className="px-4 py-3 tabular-nums">{t._count.scanEvents}</td>
                  <td className="px-4 py-3">
                    <TagStatusSelect tagId={t.id} status={t.status} />
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
