import Link from "next/link";
import type { Prisma } from "@prisma/client";
import { getStaffWith } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { can } from "@/lib/permissions";
import { pageParams } from "@/lib/pagination";
import { Forbidden } from "@/components/admin/forbidden";
import { Pagination } from "@/components/admin/pagination";
import { SearchForm } from "@/components/admin/search-form";
import { TagStatusSelect } from "./tag-status-select";

export const dynamic = "force-dynamic";

// Tags are generated by customers against QR slots they bought, so this page
// is a register of what exists rather than an inventory to hand out.
const STATUSES = ["ACTIVE", "LOST", "DEACTIVATED"] as const;
type Status = (typeof STATUSES)[number];

export default async function AdminTagsPage({
  searchParams,
}: {
  searchParams: Promise<{ status?: string; product?: string; q?: string; page?: string }>;
}) {
  const admin = await getStaffWith("tags.manage");
  if (!admin) return <Forbidden />;
  const canDeactivate = can(admin.role, "destructive");

  const sp = await searchParams;
  const status = STATUSES.includes(sp.status as Status) ? (sp.status as Status) : undefined;
  const product = sp.product || undefined;
  const q = sp.q?.trim() || undefined;
  const { page, skip, take } = pageParams(sp.page);

  const where: Prisma.TagWhereInput = {
    ...(status ? { status } : {}),
    ...(product ? { productId: product } : {}),
    ...(q
      ? {
          OR: [
            { shortCode: { contains: q, mode: "insensitive" } },
            { internalLabel: { contains: q, mode: "insensitive" } },
            { user: { email: { contains: q, mode: "insensitive" } } },
            { user: { name: { contains: q, mode: "insensitive" } } },
          ],
        }
      : {}),
  };

  const [tags, total, byStatus, products] = await Promise.all([
    prisma.tag.findMany({
      where,
      include: {
        user: { select: { id: true, name: true, email: true } },
        product: { select: { name: true } },
        theme: { select: { name: true } },
        _count: { select: { scanEvents: true } },
      },
      orderBy: { createdAt: "desc" },
      skip,
      take,
    }),
    prisma.tag.count({ where }),
    prisma.tag.groupBy({ by: ["status"], _count: { _all: true } }),
    prisma.product.findMany({ select: { id: true, name: true }, orderBy: { sortOrder: "asc" } }),
  ]);

  const count = (s: string) => byStatus.find((g) => g.status === s)?._count._all ?? 0;
  const href = (next: { status?: string; product?: string }) => {
    const query = new URLSearchParams();
    const merged = { status, product, q, ...next };
    for (const [k, v] of Object.entries(merged)) if (v) query.set(k, v);
    const qs = query.toString();
    return qs ? `/admin/tags?${qs}` : "/admin/tags";
  };
  const chip = (active: boolean) =>
    `rounded-lg border px-3 py-1.5 ${
      active
        ? "border-[var(--color-primary)] bg-[var(--color-primary)]/10 text-[var(--color-primary-dark)]"
        : "border-black/15 bg-white hover:bg-black/5"
    }`;

  return (
    <div>
      <h1 className="text-2xl font-bold">Generated QR codes</h1>
      <p className="mt-1 text-sm text-black/60">
        Every QR a customer has generated. Codes are created in the client area against purchased
        slots — there is no inventory to assign.
      </p>

      <div className="mt-5 flex flex-wrap gap-2 text-sm">
        <Link href={href({ status: "" })} className={chip(!status)}>
          All ({byStatus.reduce((n, g) => n + g._count._all, 0)})
        </Link>
        {STATUSES.map((s) => (
          <Link key={s} href={href({ status: s })} className={chip(status === s)}>
            {s} ({count(s)})
          </Link>
        ))}
      </div>

      {products.length > 0 && (
        <div className="mt-3 flex flex-wrap gap-2 text-xs">
          <Link href={href({ product: "" })} className={chip(!product)}>
            Any product
          </Link>
          {products.map((p) => (
            <Link key={p.id} href={href({ product: p.id })} className={chip(product === p.id)}>
              {p.name}
            </Link>
          ))}
        </div>
      )}

      <div className="mt-4">
        <SearchForm
          action="/admin/tags"
          placeholder="Search by code, label, or owner's name or email"
          defaultValue={q}
          keep={{ status, product }}
        />
      </div>

      <div className="mt-5 overflow-x-auto rounded-2xl border border-black/10 bg-white">
        <table className="w-full text-sm">
          <thead className="border-b border-black/10 text-left text-xs uppercase tracking-wide text-black/40">
            <tr>
              <th className="px-4 py-3 font-medium">Sticker</th>
              <th className="px-4 py-3 font-medium">Code</th>
              <th className="px-4 py-3 font-medium">Owner</th>
              <th className="px-4 py-3 font-medium">Product / theme</th>
              <th className="px-4 py-3 font-medium">Scans</th>
              <th className="px-4 py-3 font-medium">Status</th>
            </tr>
          </thead>
          <tbody>
            {tags.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-4 py-8 text-center text-black/50">
                  No QR codes match.
                </td>
              </tr>
            ) : (
              tags.map((t) => (
                <tr key={t.id} className="border-b border-black/5 last:border-b-0 align-middle">
                  <td className="px-4 py-2">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={`/api/tags/${t.id}/sticker?size=thumb`}
                      alt=""
                      loading="lazy"
                      className="h-12 w-12 rounded-lg bg-black/[0.03] object-contain"
                    />
                  </td>
                  <td className="px-4 py-3">
                    <Link href={`/admin/tags/${t.id}`} className="font-mono text-xs hover:underline">
                      /t/{t.shortCode}
                    </Link>
                    {t.internalLabel && <div className="text-xs text-black/40">{t.internalLabel}</div>}
                  </td>
                  <td className="px-4 py-3">
                    <Link href={`/admin/users/${t.user.id}`} className="hover:underline">
                      {t.user.name}
                    </Link>
                    <div className="text-xs text-black/40">{t.user.email}</div>
                  </td>
                  <td className="px-4 py-3 text-xs text-black/60">
                    {t.product?.name ?? "—"}
                    {t.theme ? ` · ${t.theme.name}` : ""}
                  </td>
                  <td className="px-4 py-3 tabular-nums">{t._count.scanEvents}</td>
                  <td className="px-4 py-3">
                    <TagStatusSelect tagId={t.id} status={t.status} canDeactivate={canDeactivate} />
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <Pagination basePath="/admin/tags" params={{ status, product, q }} page={page} total={total} />
    </div>
  );
}
